// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	auth "musiclab-be/features/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: input
func (_m *AuthService) CreateEvent(input auth.Core) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(auth.Core) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: user
func (_m *AuthService) Login(user auth.Core) (string, auth.Core, error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(auth.Core) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 auth.Core
	if rf, ok := ret.Get(1).(func(auth.Core) auth.Core); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(auth.Core)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(auth.Core) error); ok {
		r2 = rf(user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LoginOauth provides a mock function with given fields: code
func (_m *AuthService) LoginOauth(code string) error {
	ret := _m.Called(code)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: newUser
func (_m *AuthService) Register(newUser auth.Core) error {
	ret := _m.Called(newUser)

	var r0 error
	if rf, ok := ret.Get(0).(func(auth.Core) error); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthService(t mockConstructorTestingTNewAuthService) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
