// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ChatHandler is an autogenerated mock type for the ChatHandler type
type ChatHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *ChatHandler) Add() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ChatHandler) GetAll() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetByStudent provides a mock function with given fields:
func (_m *ChatHandler) GetByStudent() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewChatHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewChatHandler creates a new instance of ChatHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChatHandler(t mockConstructorTestingTNewChatHandler) *ChatHandler {
	mock := &ChatHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
