// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	classes "musiclab-be/features/classes"

	mock "github.com/stretchr/testify/mock"
)

// ClassData is an autogenerated mock type for the ClassData type
type ClassData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: mentorID, classID
func (_m *ClassData) Delete(mentorID uint, classID uint) error {
	ret := _m.Called(mentorID, classID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(mentorID, classID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMentorClass provides a mock function with given fields: mentorID, limit, offset
func (_m *ClassData) GetMentorClass(mentorID uint, limit int, offset int) ([]classes.Core, error) {
	ret := _m.Called(mentorID, limit, offset)

	var r0 []classes.Core
	if rf, ok := ret.Get(0).(func(uint, int, int) []classes.Core); ok {
		r0 = rf(mentorID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]classes.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(mentorID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMentorClassDetail provides a mock function with given fields: classID
func (_m *ClassData) GetMentorClassDetail(classID uint) (classes.Core, error) {
	ret := _m.Called(classID)

	var r0 classes.Core
	if rf, ok := ret.Get(0).(func(uint) classes.Core); ok {
		r0 = rf(classID)
	} else {
		r0 = ret.Get(0).(classes.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostClass provides a mock function with given fields: newClass
func (_m *ClassData) PostClass(newClass classes.Core) error {
	ret := _m.Called(newClass)

	var r0 error
	if rf, ok := ret.Get(0).(func(classes.Core) error); ok {
		r0 = rf(newClass)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: mentorID, classID, updatedClass
func (_m *ClassData) Update(mentorID uint, classID uint, updatedClass classes.Core) error {
	ret := _m.Called(mentorID, classID, updatedClass)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, classes.Core) error); ok {
		r0 = rf(mentorID, classID, updatedClass)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClassData interface {
	mock.TestingT
	Cleanup(func())
}

// NewClassData creates a new instance of ClassData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClassData(t mockConstructorTestingTNewClassData) *ClassData {
	mock := &ClassData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
