// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	instruments "musiclab-be/features/instruments"

	mock "github.com/stretchr/testify/mock"
)

// InstrumentService is an autogenerated mock type for the InstrumentService type
type InstrumentService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: mentorID, instrumentID
func (_m *InstrumentService) Delete(mentorID uint, instrumentID uint) error {
	ret := _m.Called(mentorID, instrumentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(mentorID, instrumentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: input
func (_m *InstrumentService) Insert(input instruments.MentorInstrumentCore) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(instruments.MentorInstrumentCore) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectAll provides a mock function with given fields:
func (_m *InstrumentService) SelectAll() ([]instruments.Core, error) {
	ret := _m.Called()

	var r0 []instruments.Core
	if rf, ok := ret.Get(0).(func() []instruments.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]instruments.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectAllByMentorID provides a mock function with given fields: mentorID
func (_m *InstrumentService) SelectAllByMentorID(mentorID uint) ([]instruments.MentorInstrumentCore, error) {
	ret := _m.Called(mentorID)

	var r0 []instruments.MentorInstrumentCore
	if rf, ok := ret.Get(0).(func(uint) []instruments.MentorInstrumentCore); ok {
		r0 = rf(mentorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]instruments.MentorInstrumentCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(mentorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInstrumentService interface {
	mock.TestingT
	Cleanup(func())
}

// NewInstrumentService creates a new instance of InstrumentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInstrumentService(t mockConstructorTestingTNewInstrumentService) *InstrumentService {
	mock := &InstrumentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
