// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	reviews "musiclab-be/features/reviews"

	mock "github.com/stretchr/testify/mock"
)

// ReviewService is an autogenerated mock type for the ReviewService type
type ReviewService struct {
	mock.Mock
}

// GetMentorReview provides a mock function with given fields: page, limit, mentorID
func (_m *ReviewService) GetMentorReview(page int, limit int, mentorID uint) ([]reviews.Core, error) {
	ret := _m.Called(page, limit, mentorID)

	var r0 []reviews.Core
	if rf, ok := ret.Get(0).(func(int, int, uint) []reviews.Core); ok {
		r0 = rf(page, limit, mentorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reviews.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, uint) error); ok {
		r1 = rf(page, limit, mentorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostMentorReview provides a mock function with given fields: mentorID, newReview
func (_m *ReviewService) PostMentorReview(mentorID uint, newReview reviews.Core) error {
	ret := _m.Called(mentorID, newReview)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, reviews.Core) error); ok {
		r0 = rf(mentorID, newReview)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewReviewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewReviewService creates a new instance of ReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReviewService(t mockConstructorTestingTNewReviewService) *ReviewService {
	mock := &ReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
